# Welcome to serverless. Read the docs
# https://serverless.com/framework/docs/

# Serverless.yml is the configuration the CLI
# uses to deploy your code to your provider of choice

# The `service` block is the name of the service
service: stripe-payment-lambda

# Configuration variables
custom:
  stages:
    - dev
    - prod
  secrets:
    dev: ${file(secrets.dev.json)}
    prod: ${file(secrets.prod.json)}

# The `provider` block defines where your service will be deployed
provider:
  name: aws
  apiKeys:
    - ${self:provider.stage}-key
  runtime: nodejs6.10
  stage: ${opt:stage,'dev'}
  environment:
    STRIPE_SECRET_KEY: ${self:custom.secrets.${self:provider.stage}.stripeSecretKey}

# The `functions` block defines what code to deploy
functions:
  checkout:
    handler: checkout.handler
    # The `events` block defines how to trigger the handler.createCharge code
    events:
      - http:
          path: checkout
          method: post
          private: true
          cors: true
